### ISSUE TITLE
Add option to raise internal limits

### ISSUE THREAD

**Issue by Corecii** [JohnnyMorganz/luau-analyze-rojo#11]
With complex, fully-typed code I'm running into `Internal error: Code is too complex to typecheck! Consider adding type annotations around this area` a lot. Being able to even fix this code to get it typechecked is hard when the typechecker quits with little explanation! It would be nice to raise the limits -- at least temporarily -- so that projects can at minimum be fully typechecked internally without complex workarounds.

**Comment by Corecii** [comment]
I've actually done some work to try this out and it solved my issue:

https://github.com/JohnnyMorganz/luau-analyze-rojo/compare/master...Corecii:add-limit-options

I have *no idea* how correct this is, all I know is that it works. This is pretty much the first time I've ever touched C++!

I'd appreciate this being done properly by someone that knows what they're doing. It seems like it would be pretty easy to add, right?

**Comment by JohnnyMorganz** [comment]
I'm not too knowledgeable on C++ either 😛, but this looks correct to me.

Feel free to open a PR for it

**Comment by Corecii** [comment]
Great! I'll do that today or tomorrow. 👍

These additional options should be shown in the `--help` response too, right? If so I'll make sure to add that before making a PR. Only asking because they're kind of lengthy. I'd really rather see these in a config file or similar, but command line parameters will have to do for now due to my limited C++ knowledge.

**Comment by JohnnyMorganz** [comment]
Yeah, but I would probably put them under a different subheading after "Available options" just to separate them a bit.

It would be great if you could also quickly write something about it on the README too

**Comment by JohnnyMorganz** [comment]
@Corecii just an FYI in case you are still interested in the more general flag version - Luau upstream just pushed an update to the `CLI/Repl.cpp` tool to allow passing in any flag. It might be helpful: https://github.com/Roblox/luau/commit/e0a6461173216b76bdf731410f50485b89c83aa4#diff-998ee781e91075902c735691b7e43aa84aa16ff7b62677e06eca7ce82988f3ac
