### ISSUE TITLE
Add support for `.luaurc` in the virtual file path

### ISSUE THREAD

**Issue by vocksel** [JohnnyMorganz/luau-analyze-rojo#34]
I'm trying to include a .luaurc in my Packages folder so I can ignore it from typechecking, however including Packages/.luaurc with the following contents does not seem to work:

```json
{
    "languageMode": "nocheck",
    "lint": { 
        "*": true
    }
}
```

As mentioned over Discord, "right now it’s not converting the virtual instance path to a real file path to search a config file for." As such it would be great if support could be added to convert .luaurc config files into the virtual file path so that certain directories can be ignored

**Comment by JohnnyMorganz** [comment]
Fixed in https://github.com/JohnnyMorganz/luau-analyze-rojo/commit/1b9ea41720d46563b159155f79fb1a79a2a5a898
