### ISSUE TITLE
Allow for multiple type definition files

### ISSUE THREAD

**Issue by Gargafield** [JohnnyMorganz/luau-analyze-rojo#4]
Allow the `--defs` option to be passed comma separated definition files. Example: `--defs=global types.d.lua,myLibrary.d.lua`

**Comment by JohnnyMorganz** [comment]
Added in https://github.com/JohnnyMorganz/luau-analyze-rojo/commit/92da4f75ac3fdd008b96e397190aae43cc59f17f, however the syntax is through using `--defs` multiple times.

e.g. `luau-analyze-rojo --defs=globalTypes.d.lua --defs=myLibrary.d.lua source.lua`
